version: '3'

tasks:
  img:
    cmds:
      - docker images 
    silent: true

  run-*:
    vars:
      IMG: '{{index .MATCH 0}}'
    cmds:
      - docker run --rm -it {{.IMG}} sh

  bld-*:
    vars:
      IMG: '{{index .MATCH 0}}'
    cmds:
      - docker build . -t {{.IMG}}

  rmi-*:
    vars:
      IMG: '{{index .MATCH 0}}'
    cmds:
      - docker rmi {{.IMG}}

  cclean:
    cmds:
      - docker ps -a -q | xargs docker rm

  socks:
    cmds:
      - ssh -i ~/.ssh/id_rsa -D 1337 -f -C -q -N bdereims@forty-two

  start-nfs_server:
    cmds:
      - docker run                     \
        -v /data:/data                 \
        -v exports.txt:/etc/exports:ro \
        --cap-add SYS_ADMIN            \
        -p 2049:2049 nfs_server                           
